[package]
name = "physarum-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = { version = "0.19", features = ["spirv"]}
rand = "0.8"
bytemuck = { version = "1.12", features = ["derive"] }
nannou_wgpu = "0.19.0"
